MENU:
  FIRST:
    NAME: "Name"
    LORE:
      - ""
      - ""
      - ""
    # In case u want to get a rank using this, set give_rank to true and on rank put the rank u wanna give
    GIVE_RANK: false
    RANK: ""
    GIVE_PERMISSION: false
    PERMISSION: ""
    COST: 100
