JOIN_ITEM:
  DISPLAYNAME: "&aJungly Store &7(Click Derecho)"
  MATERIAL: CHEST
  DATA: 0
  SLOT: 5
  AMOUNT: 1
  LORE:
    - ""
    - "&fUsa &aclick derecho &fpara entrar en la tienda"
    - ""

GIVE_JOIN_ITEM: true